2025-05-12 13:20:43,811 — INFO — File Processing starts ...
2025-05-12 13:20:43,811 — INFO — START TIME::: 2025-05-12 13:20:43.810376
2025-05-12 13:20:43,811 — INFO — E:\Python\FileConverter_Miscelleneous\INPUT\
2025-05-12 13:20:43,812 — INFO — ********************Internal PHP Correction.xlsx*****************************
2025-05-12 13:20:43,812 — INFO — LoopCount: 1
2025-05-12 13:20:55,026 — INFO — ['Sheet1', 'Sheet2', 'Sheet3']
2025-05-12 13:20:55,027 — INFO — Processing File: Internal PHP Correction.xlsx
2025-05-12 13:20:55,027 — INFO — Processing sheet: Sheet1
2025-05-12 13:20:55,027 — INFO — ResponseFile to be processed: E:\Python\FileConverter_Miscelleneous\ResponseFile\COOKIE-321478_Sheet1.txt
2025-05-12 13:20:55,028 — INFO — INSIDE ReadingTheFileDF WITH FILE: Internal PHP Correction.xlsx
2025-05-12 13:21:06,928 — INFO — DATA CONVERTED FROM XLS TO DF
2025-05-12 13:21:06,985 — INFO — DATA FORMATTED FROM DF TO DF1
2025-05-12 13:21:07,037 — INFO — DATA FORMATTED FROM DF1 TO DF2
2025-05-12 13:21:07,038 — INFO — DATA FORMATTED FROM DF2 TO DF3
2025-05-12 13:21:17,960 — INFO — ********************~$Internal PHP Correction.xlsx*****************************
2025-05-12 13:21:17,961 — INFO — LoopCount: 2
2025-05-12 13:21:17,961 — INFO — []
2025-05-12 13:21:17,962 — INFO — Please provide correct sheet name
2025-05-12 13:21:17,962 — ERROR — ERROR IN BLOCK
Traceback (most recent call last):
  File "E:\Python\BehaveBDD\Python312\Lib\shutil.py", line 886, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'E:\\Python\\FileConverter_Miscelleneous\\INPUT\\~$Internal PHP Correction.xlsx' -> 'E:\\Python\\FileConverter_Miscelleneous\\OUT\\~$Internal PHP Correction.xlsx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python\FileConverter_Miscelleneous\FileConverter.py", line 339, in <module>
    shutil.move(InputDir + FileName, OutputDir + FileName)
  File "E:\Python\BehaveBDD\Python312\Lib\shutil.py", line 906, in move
    copy_function(src, real_dst)
  File "E:\Python\BehaveBDD\Python312\Lib\shutil.py", line 460, in copy2
    _winapi.CopyFile2(src_, dst_, flags)
FileNotFoundError: [WinError 2] The system cannot find the file specified
